theme = "trans_carb"

[editor]
default-line-ending = "lf"
shell = ["nu", "-c"]
color-modes = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[editor.statusline]
right = ["workspace-diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
display-progress-messages = true

[editor.cursor-shape]
normal = "bar"
insert = "bar"
select = "underline"
