# rust
[[language]]
name = "anecte"
scope = "source.anecte"
file-types = ["anct"]
grammar = "scheme"

[language-server.rust-analyzer.config]
check = { command = "clippy" }

# kotlin
[[language]]
name = "kotlin"
scope = "source.kotlin"
file-types = ["kt", "kts"]
roots = ["settings.gradle", "settings.gradle.kts"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "    " }
language-servers = [ "kotlin-lsp" ]

[language-server]
kotlin-lsp = { command = "kotlin-lsp", args = ["--stdio"] }
